### ISSUE TITLE
Add CSS file for tweaks

### ISSUE THREAD

**Issue by tessak22** [fast-af/devportal#13]
Let's find a way to easily manipulate CSS on multiple pages.  

Notes from Redocly:
For CSS, you can add a stylesheet which will be imported into every page of the site. It should be added into the static folder, and included in the siteConfig.yaml in the stylesheets section:

https://github.com/Redocly/developer-portal-starter/blob/master/siteConfig.yaml#L10

However, if you want to add CSS only to a specific page, you can do that by adding the <style> tag inline to the page.

[Theme documentation](https://redoc.ly/docs/developer-portal/theme/)

**Comment by kaitlynhova** [comment]
out of date issue -- docs 2.0 site launched 11.4.21
