### ISSUE TITLE
[REQUEST] BigCommerce Fast Checkout Buttons on Product Category Pages

### ISSUE THREAD

**Issue by tessak22** [fast-af/devportal#20]
## Request Details
URL to the **final, approved** doc in Notion: Needs to be written
Ideal publish by date: 5/21/2021
Sidebar section, see options below: BigCommerce

**Additional context**
Requested by a client and discussed in sales-engineering in Slack.

**Comment by kaitlynhova** [comment]
out of date issue -- docs 2.0 site launched 11.4.21
